version: '3.9'

services:
  app:
    container_name: sentrycreactapp
    image: 'sentrycreactapp:latest-1'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9898:9898
    volumes:
      - sentrycvol:/var/lib/sentryc/vol
volumes:
  sentrycvol: {}